# Generated by Django 2.1.2 on 2018-10-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                help_text='Required. Email allows you reset password.',
                max_length=150,
                verbose_name='email address'
            ),
        ),
    ]
