# Generated by Django 2.1.2 on 2018-11-05 20:02

from django.db import migrations, models
import template.models
import template.validators


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_create_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='file',
            field=models.FileField(
                upload_to=template.models._user_directory_path,
                validators=[
                    template.validators.HtmlExtensionValidator()
                ],
                verbose_name='template file'),
        ),
    ]
