# Generated by Django 2.1.2 on 2018-11-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0004_templatehelper'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatehelper',
            name='file',
            field=models.CharField(
                blank=True,
                null=True,
                default=None,
                max_length=260
            ),
        ),
    ]
